# Generated by Django 4.0.4 on 2022-06-01 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider_Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basefare', models.FloatField()),
                ('basekm', models.FloatField()),
                ('distance', models.FloatField(blank=True)),
                ('price_per_km', models.FloatField(blank=True)),
                ('total_price', models.FloatField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User_pick_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_truck_type', models.CharField(choices=[('tata 407', 'tata 407'), ('blero', 'blero')], max_length=150)),
                ('pick_point', models.CharField(max_length=256)),
                ('drop_point', models.CharField(max_length=256)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.rider_trip')),
            ],
        ),
    ]
