# Generated by Django 4.0.4 on 2022-06-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_pick_form',
            name='admin',
        ),
    ]
