# Generated by Django 4.0.4 on 2022-06-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike_trip',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='blero_8ft_trip',
            name='blero_id',
        ),
        migrations.RemoveField(
            model_name='champion_trip',
            name='champion_id',
        ),
        migrations.RemoveField(
            model_name='confirm_booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ecovan_trip',
            name='ecovan_id',
        ),
        migrations.RemoveField(
            model_name='maruti_suzuki_super_carry_trip',
            name='maruti_id',
        ),
        migrations.RemoveField(
            model_name='tata_ace_7ft_trip',
            name='tata_7ft_id',
        ),
        migrations.RemoveField(
            model_name='tata_ace_8ft_trip',
            name='tata_8ft_id',
        ),
    ]
