# Generated by Django 4.0.4 on 2022-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_remove_user_pick_form_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider_trip',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='rider_trip',
            name='total_price',
        ),
        migrations.AddField(
            model_name='user_pick_form',
            name='distance',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user_pick_form',
            name='total_price',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
    ]
