# Generated by Django 4.0.4 on 2022-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_remove_bike_trip_bike_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_point', models.CharField(blank=True, max_length=256, null=True)),
                ('drop_point', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.FloatField()),
                ('distance', models.FloatField()),
                ('vehicle', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
