# Generated by Django 4.0.4 on 2022-06-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_champion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_type',
            old_name='vehicle_type1',
            new_name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle_type',
            name='vehicle_type2',
        ),
        migrations.RemoveField(
            model_name='vehicle_type',
            name='vehicle_type3',
        ),
        migrations.RemoveField(
            model_name='vehicle_type',
            name='vehicle_type4',
        ),
        migrations.RemoveField(
            model_name='vehicle_type',
            name='vehicle_type5',
        ),
        migrations.RemoveField(
            model_name='vehicle_type',
            name='vehicle_type6',
        ),
        migrations.RemoveField(
            model_name='vehicle_type',
            name='vehicle_type7',
        ),
    ]
