# Generated by Django 4.0.4 on 2022-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_alter_rider_trip_price_per_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider_trip',
            old_name='price_per_km',
            new_name='extra1_distance',
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='extra2_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='extra3_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='extra4_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='extra5_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='extra6_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='price1_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='price2_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='price3_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='price4_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='price5_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_trip',
            name='price6_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
