# Generated by Django 4.0.4 on 2022-06-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_vehicle_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_type',
            name='name',
        ),
    ]
