# Generated by Django 4.0.4 on 2022-06-27 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0006_remove_vehicle_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_booking',
            name='user_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
