# Generated by Django 4.0.4 on 2022-06-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_alter_confirm_booking_user_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm_booking',
            old_name='user_vehicle',
            new_name='user_id',
        ),
    ]
