# Generated by Django 4.0.4 on 2022-06-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_champion_trip_ecovan_trip_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_pick_form',
        ),
    ]
