# Generated by Django 4.0.4 on 2022-06-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ride', '0005_vehicle_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PICKFORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_point', models.CharField(max_length=256)),
                ('drop_point', models.CharField(max_length=256)),
                ('distance', models.FloatField(blank=True, max_length=256, null=True)),
                ('price_t', models.FloatField(blank=True, max_length=256, null=True)),
                ('user_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Userform.pickform')),
            ],
        ),
    ]
