# Generated by Django 4.0.4 on 2022-06-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickform',
            old_name='distance',
            new_name='distance_with_Bike',
        ),
        migrations.RenameField(
            model_name='pickform',
            old_name='total_price',
            new_name='distance_with_Blero_8FT',
        ),
        migrations.AddField(
            model_name='pickform',
            name='distance_with_Champion',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='distance_with_Ecovan',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='distance_with_Maruti',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='distance_with_Tata_ace_7FT',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='distance_with_Tata_ace_8FT',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='total_price_Bike',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='total_price_Blero_8FT',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='total_price_Champion',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='total_price_Ecovan',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='total_price_Maruti',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='total_price_Tata_ace_7FT',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pickform',
            name='total_price_Tata_ace_8FT',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
    ]
