# Generated by Django 4.0.4 on 2022-06-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Confirm_Booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm_booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
